---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebookapp-deploy
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: phonebookapp
  template:
    metadata:
      name: phonebookapp-pod
      labels:
        app: phonebookapp
    spec:
      containers:
        - name: phonebookapp-container
          image: ybinds/phonebookapp
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: phonebookapp-svc
spec:
  type: NodePort
  selector:
    app: phonebookapp
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30002
...